### ISSUE TITLE
Can't start netbox

### ISSUE THREAD

**Issue by alitheg** [pitkley/docker-netbox#23]
On trying to run, as of the latest version (may be a netbox update - I'm investigating), I get:

```django.template.library.InvalidTemplateLibrary: Invalid template library specified. ImportError raised when trying to load 'django_rq.templatetags.django_rq': cannot import name 'UnpickleError' from 'rq.exceptions' (/usr/local/lib/python3.8/site-packages/rq/exceptions.py)```

**Comment by alitheg** [comment]
Looks like it was fixed [here](https://github.com/netbox-community/netbox/issues/4633)

**Comment by pitkley** [comment]
Hi @alitheg, thank you for notifying me of this and finding the relevant change. I have updated the repository to the latest Netbox commit (and ensured that updates will happen automatically again).

AFAICT the issue is fixed, the latest `pitkley/netbox:latest` image is working fine for me now! Can you confirm?

**Comment by alitheg** [comment]
Yup, that fixed it! Though I then had to do some manual mangling in the migrations table because some migrations were renamed [in the repo](https://github.com/netbox-community/netbox/commit/6e832de4a99c9a45d4155023162f1b25b84bf62f). 

Thanks for your help!

**Comment by pitkley** [comment]
Ugh, the migration-renaming is unfortunate. :confused: Anyway, thanks for letting me know that it works again! :+1:
