### ISSUE TITLE
Time zone variable

### ISSUE THREAD

**Issue by hrv231** [pitkley/docker-netbox#45]
Hello,

I'm trying to change the default UTC TIME_ZONE under the configurations.py, and every time I restart, the configuration gets lost.
I'm trying to do the following:
![image](https://user-images.githubusercontent.com/41212308/105802900-096c1500-5f51-11eb-9eac-de0e116c6d0d.png)

The good thing is that I tried the LOGIN_REQUIRED and it worked.
Running this docker on unraid.

I think you need to add more information on your documentation, but so far, really good work!!

Thanks.

**Comment by pitkley** [comment]
Hi @hrv231. I just merged #46 which should add support for setting the `TIME_ZONE` variable. An updated image should be available on Docker Hub within the next 30-90 minutes.

(Please note that this project is not really maintained anymore, mostly because I no longer use it myself. If there is any documentation you'd like to see that you might be able to contribute, I'd be happy to review PRs!)
