### ISSUE TITLE
Error while executing command "docker-compose run --rm netbox createsuperuser"

### ISSUE THREAD

**Issue by ghost** [pitkley/docker-netbox#8]
[root@xxx ~]# docker-compose run --rm netbox createsuperuser
Starting root_db_1 ... done

Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 302, in execute
    settings.INSTALLED_APPS
  File "/usr/local/lib/python2.7/site-packages/django/conf/__init__.py", line 55, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python2.7/site-packages/django/conf/__init__.py", line 43, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python2.7/site-packages/django/conf/__init__.py", line 99, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/local/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/src/netbox/netbox/netbox/settings.py", line 8, in <module>
    import configuration
  File "/usr/src/netbox/netbox/netbox/configuration.py", line 26
SyntaxError: Non-ASCII character '\xc3' in file /usr/src/netbox/netbox/netbox/configuration.py on line 26, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

**Comment by pitkley** [comment]
Line 26 in `configuration.py` should be the `SECRET_KEY`. From the error message I assume that you have chosen a secret-key which includes non-ASCII characters. Is that correct?

If so, can you try a secret-key with only ASCII characters?

**Comment by ghost** [comment]
Tried and it worked removing the non-ASCII characters.
However, I received the following message:

  212 static files copied to '/usr/src/netbox/netbox/static'.
  **Couldn't import dot_parser, loading of dot files will not be possible.**
  Username (leave blank to use 'netbox'):
  Email address:
  Password:
  Password (again):
  Superuser created successfully.

Is the bolded line a blocking problem? Which effect should I expect due to this message?

**Comment by pitkley** [comment]
It could mean that you are not able to render topology maps. If you navigate to any site you have added under "Organization", in the bottom right you should see a panel called "Topology Maps" with a link to your site-map.

Try opening that map. If it renders and you don't receive an error, you should be able to ignore the error. Otherwise there might be some issue, although my guess would be that it is upstream.

**Comment by ghost** [comment]
Thanks for your support!
I don't see any map; once the site is created, I see the following blank menu:

![image](https://user-images.githubusercontent.com/33869249/33330043-17d1472c-d45e-11e7-8406-996c6d971644.png)

**Comment by pitkley** [comment]
I have just checked the [Netbox documentation](https://netbox.readthedocs.io/en/latest/data-model/extras/#topology-maps), you have to create a topology map manually through the Netbox admin UI. If you create one and have issues with rendering it, it might be related to the error you posted.

Otherwise topology maps (and Netbox functionality in general) are out of scope of this Docker image and would have to be relayed upstream.

**Comment by madbutterflies** [comment]
I have a similiar issue. I'm using Debian (jessie) on a virtual machine (accessed through a putty terminal) and end up with the same error. The result I get on the 8000 port is:
![24740450_1783642121668755_1099196215_n](https://user-images.githubusercontent.com/26737970/33612006-8f68a010-d9d0-11e7-8685-b724e32eb1ca.png)

Sadly, since I'm a newbie I don't really understand what I have to do from the above posts in my case. Can I ask for a more specific explanation?

**Comment by ghost** [comment]
I think it's better if you open a different issue, this problem seems different from mine (when you open it, please paste the content of your "docker-compose.yml").

**Comment by Ondjultomte** [comment]
madbutter:
Edit:
- "ALLOWED_HOSTS=netbox.dev localhost" 
and add you fqdn and or IP
